<?php

use Pineapple\ReportError\Block\ReportError;
use Magento\Framework\Escaper;

/**
 * @var ReportError $block
 * @var Escaper $escaper
 */
?>

<hr>
<div class="title"><strong><?= $escaper->escapeHtml(__('Report Error')) ?></strong></div>
<div class="content">
    <form class="form report" method="post"
          action="<?= $escaper->escapeHtml($block->getFormActionUrl()) ?>"
          id="report-error">
        <div class="field report-error">
            <div class="control">
                <label for="error">
                    <span class="label"><?= $escaper->escapeHtml(__('Report an error')) ?></span>
                    <input name="error" type="text" id="error"
                           placeholder="<?= $escaper->escapeHtml(__('Enter a description of the error')) ?>"
                           data-mage-init='{"mage/trim-input":{}}'
                           data-validate="{required:true}"/>
                </label>
            </div>
        </div>
        <div class="actions">
            <button class="action primary" title="<?= $escaper->escapeHtml(__('Send')) ?>"
                    type="submit" aria-label="Send">
                <span><?= $escaper->escapeHtml(__('Send')) ?></span>
            </button>
        </div>
    </form>
</div>

<script type="text/javascript">
    require([
        'Magento_Ui/js/modal/alert',
        'jquery'
    ], function (alert, $) {
        $('form.report').on('submit', function (event) {
            event.preventDefault();

            var errorText = $('#error').val()
            console.log(errorText)

            alert({
                title: $.mage.__('Thanks, message sent'),
                content: errorText
            })
        })
    })
</script>





